#!/usr/bin/env python3
"""Generate crawlable SEO pages from the public storefront catalog.

The source website remains a lightweight GitHub Pages site. This script makes the
commercial content available as static HTML for search engines, social crawlers,
and non-JavaScript clients while preserving the existing interactive storefront.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote, urlparse

ROOT = Path(__file__).resolve().parents[1]
INDEX_PATH = ROOT / "index.html"
STOREFRONT_JS_PATH = ROOT / "shop" / "storefront.js"
STOREFRONT_CSS_PATH = ROOT / "shop" / "storefront.css"
PRODUCTS_DIR = ROOT / "products"
SHOP_DIR = ROOT / "shop"
CARE_DIR = ROOT / "care-guides"
BASE_URL = "https://rrereptiles.com"
BUSINESS_NAME = "Red Rocks Exotic Reptiles"
BUSINESS_EMAIL = "rrereptiles@gmail.com"
BUSINESS_PHONE_DISPLAY = "970-400-1278"
BUSINESS_PHONE_E164 = "+1-970-400-1278"
DEFAULT_IMAGE = f"{BASE_URL}/images/Logo%20Letters.png"
LOGO_URL = f"{BASE_URL}/images/Logo.svg"
GENERATED_COMMENT = "<!-- Generated by scripts/build_seo.py. Do not hand-edit. -->"
TODAY = datetime.now(timezone.utc).date().isoformat()

SOCIAL_URLS = [
    "https://www.instagram.com/red_rocks_reptiles/",
    "https://www.facebook.com/RREReptiles",
    "https://www.tiktok.com/@redrocks_exotic_reptiles",
    "https://www.youtube.com/@RedRocksExoticReptiles",
    "https://www.morphmarket.com/stores/red_rocks_exotic_reptiles/",
]

CATEGORY_GROUPS: dict[str, dict[str, Any]] = {
    "reptiles": {
        "title": "Reptiles for Sale in Colorado",
        "short": "Reptiles",
        "description": (
            "Browse available captive-bred geckos, skinks, lizards, and snakes from "
            "Red Rocks Exotic Reptiles, a Colorado reptile breeder and online store."
        ),
        "categories": {"animal", "animals", "reptile", "reptiles", "geckos-crested", "geckos-other"},
        "keywords": "reptiles for sale Colorado, geckos for sale, reptile breeder Colorado",
    },
    "reptile-supplies": {
        "title": "Reptile Supplies & Enclosure Accessories",
        "short": "Reptile Supplies",
        "description": (
            "Shop reptile husbandry supplies, custom hides, feeding ledges, bowls, "
            "supplements, enclosure accessories, and 3D-printed reptile products."
        ),
        "categories": {"husbandry-supplies", "dietary-supplements"},
        "keywords": "reptile supplies Colorado, reptile enclosure accessories, reptile hides",
    },
    "feeders": {
        "title": "Live Feeder Insects in Colorado",
        "short": "Feeder Insects",
        "description": (
            "Check local availability for crickets, mealworms, superworms, dubia roaches, "
            "fruit fly cultures, isopods, and other reptile feeders. Local pickup only."
        ),
        "categories": {"feeders"},
        "keywords": "feeder insects Colorado, live crickets near me, dubia roaches Colorado",
    },
    "aquatic-plants": {
        "title": "Aquatic Plants & Freshwater Aquarium Plants",
        "short": "Aquatic Plants",
        "description": (
            "Shop fully submerged-grown freshwater aquarium plants, including swords, "
            "mosses, stem plants, floaters, and other aquatic plants from Colorado."
        ),
        "categories": {"plants", "shrimp", "tropical-plants"},
        "keywords": "aquatic plants Colorado, freshwater aquarium plants, aquarium plants online",
    },
    "entomology-art": {
        "title": "Entomology Art & Insect Displays",
        "short": "Entomology Art",
        "description": (
            "Browse handcrafted pinned insect displays, floating frames, shadow boxes, "
            "and custom entomology art from Red Rocks Exotic Reptiles."
        ),
        "categories": {"entomology"},
        "keywords": "entomology art, pinned insect display, insect shadow box",
    },
}

CATEGORY_LABELS = {
    "animal": "Animals",
    "animals": "Animals",
    "reptile": "Animals",
    "reptiles": "Animals",
    "geckos-crested": "Animals",
    "geckos-other": "Animals",
    "husbandry-supplies": "Husbandry Supplies",
    "dietary-supplements": "Diet & Supplements",
    "feeders": "Feeder Insects",
    "plants": "Aquatic Plants",
    "tropical-plants": "Tropical Plants",
    "shrimp": "Freshwater Shrimp",
    "entomology": "Entomology Art",
}


def escape(value: Any) -> str:
    return html.escape(str(value or ""), quote=True)


def compact_text(value: Any, fallback: str = "") -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    return text or fallback


def json_script(data: Any) -> str:
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return payload.replace("</", "<\\/")


def absolute_url(value: str | None) -> str:
    if not value:
        return DEFAULT_IMAGE
    value = value.strip()
    if value.startswith("https://") or value.startswith("http://"):
        return value
    return f"{BASE_URL}/{value.lstrip('/')}"


def read_storefront_config() -> tuple[str, str]:
    text = STOREFRONT_JS_PATH.read_text(encoding="utf-8")
    url_match = re.search(r"const SUPABASE_URL = '([^']+)'", text)
    key_match = re.search(r"const SUPABASE_PUBLISHABLE_KEY = '([^']+)'", text)
    if not url_match or not key_match:
        raise RuntimeError("Could not read the public Supabase storefront configuration.")
    return url_match.group(1), key_match.group(1)


def fetch_catalog(fixture: Path | None = None) -> list[dict[str, Any]]:
    if fixture:
        payload = json.loads(fixture.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            payload = payload.get("products", [])
        if not isinstance(payload, list):
            raise RuntimeError("Catalog fixture must be a JSON array or contain a products array.")
        return [dict(row) for row in payload]

    supabase_url, publishable_key = read_storefront_config()
    request = urllib.request.Request(
        f"{supabase_url}/rest/v1/rpc/get_storefront_catalog",
        data=b"{}",
        method="POST",
        headers={
            "apikey": publishable_key,
            "Authorization": f"Bearer {publishable_key}",
            "Content-Type": "application/json",
            "User-Agent": "RRE-SEO-Generator/1.0",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.load(response)
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as error:
        raise RuntimeError(f"Could not load the public storefront catalog: {error}") from error
    if not isinstance(payload, list):
        raise RuntimeError("The storefront catalog response was not a JSON array.")
    return [dict(row) for row in payload]


def product_group(product: dict[str, Any]) -> str:
    category = compact_text(product.get("store_category"))
    for slug, config in CATEGORY_GROUPS.items():
        if category in config["categories"]:
            return slug
    return "reptile-supplies"


def product_url(product: dict[str, Any]) -> str:
    slug = compact_text(product.get("slug"), f"item-{product.get('item_id', 'product')}")
    return f"{BASE_URL}/products/{quote(slug, safe='-')}.html"


def product_description(product: dict[str, Any]) -> str:
    description = compact_text(product.get("description") or product.get("short_description"))
    if description:
        return description
    group = CATEGORY_GROUPS[product_group(product)]
    return f"{compact_text(product.get('public_name'), 'Product')} from {BUSINESS_NAME}. {group['description']}"


def availability_schema(product: dict[str, Any]) -> str:
    return "https://schema.org/InStock" if product.get("in_stock") else "https://schema.org/OutOfStock"


def business_schema() -> dict[str, Any]:
    return {
        "@type": ["PetStore", "OnlineStore"],
        "@id": f"{BASE_URL}/#business",
        "name": BUSINESS_NAME,
        "legalName": "Red Rocks Exotic Reptiles LLC",
        "url": f"{BASE_URL}/",
        "logo": {"@type": "ImageObject", "url": LOGO_URL},
        "image": DEFAULT_IMAGE,
        "description": (
            "Colorado reptile store and ethical breeder offering captive-bred reptiles, "
            "feeder insects, reptile supplies, aquatic plants, and custom enclosure accessories."
        ),
        "telephone": BUSINESS_PHONE_E164,
        "email": BUSINESS_EMAIL,
        "priceRange": "$-$$$",
        "areaServed": [
            {"@type": "State", "name": "Colorado"},
            {"@type": "AdministrativeArea", "name": "Colorado Front Range"},
            {"@type": "Country", "name": "United States"},
        ],
        "sameAs": SOCIAL_URLS,
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": BUSINESS_PHONE_E164,
            "email": BUSINESS_EMAIL,
            "contactType": "customer service",
            "areaServed": "US",
            "availableLanguage": "English",
        },
    }


def home_schema() -> dict[str, Any]:
    return {
        "@context": "https://schema.org",
        "@graph": [
            business_schema(),
            {
                "@type": "WebSite",
                "@id": f"{BASE_URL}/#website",
                "url": f"{BASE_URL}/",
                "name": BUSINESS_NAME,
                "alternateName": ["RRE Reptiles", "Red Rocks Reptiles"],
                "publisher": {"@id": f"{BASE_URL}/#business"},
                "inLanguage": "en-US",
            },
            {
                "@type": "WebPage",
                "@id": f"{BASE_URL}/#webpage",
                "url": f"{BASE_URL}/",
                "name": "Colorado Reptile Store & Breeder | Red Rocks Exotic Reptiles",
                "description": (
                    "Shop ethically bred reptiles, feeder insects, reptile supplies, aquatic plants, "
                    "and custom enclosure accessories from a Colorado reptile store."
                ),
                "isPartOf": {"@id": f"{BASE_URL}/#website"},
                "about": {"@id": f"{BASE_URL}/#business"},
                "inLanguage": "en-US",
            },
        ],
    }


def replace_meta(html_text: str, pattern: str, replacement: str) -> str:
    if re.search(pattern, html_text, flags=re.IGNORECASE):
        return re.sub(pattern, replacement, html_text, count=1, flags=re.IGNORECASE)
    if "</head>" not in html_text:
        raise RuntimeError("Could not find </head> while adding metadata.")
    return html_text.replace("</head>", f"    {replacement}\n</head>", 1)


def patch_index() -> None:
    text = INDEX_PATH.read_text(encoding="utf-8")
    original = text
    title = "Colorado Reptile Store & Breeder | Red Rocks Exotic Reptiles"
    description = (
        "Shop ethically bred reptiles, feeder insects, reptile supplies, aquatic plants, and "
        "custom enclosure accessories from a Colorado reptile store. Shipping and local pickup available."
    )
    text = re.sub(r"<title>.*?</title>", f"<title>{escape(title)}</title>", text, count=1, flags=re.DOTALL)
    text = replace_meta(text, r'<meta\s+name="description"\s+content="[^"]*"\s*/?>', f'<meta name="description" content="{escape(description)}">')
    text = replace_meta(text, r'<meta\s+property="og:title"\s+content="[^"]*"\s*/?>', f'<meta property="og:title" content="{escape(title)}">')
    text = replace_meta(text, r'<meta\s+property="og:description"\s+content="[^"]*"\s*/?>', f'<meta property="og:description" content="{escape(description)}">')
    text = replace_meta(text, r'<meta\s+name="twitter:title"\s+content="[^"]*"\s*/?>', f'<meta name="twitter:title" content="{escape(title)}">')
    text = replace_meta(text, r'<meta\s+name="twitter:description"\s+content="[^"]*"\s*/?>', f'<meta name="twitter:description" content="{escape(description)}">')
    text = replace_meta(text, r'<meta\s+name="keywords"\s+content="[^"]*"\s*/?>', '<meta name="keywords" content="reptile store Colorado, reptiles for sale Colorado, reptile breeder, feeder insects, reptile supplies, aquatic plants">')

    # Replace the original single-object schema with a fuller graph. The markers make future runs idempotent.
    schema_block = (
        "    <!-- SEO-SCHEMA:BEGIN -->\n"
        f"    <script type=\"application/ld+json\">{json_script(home_schema())}</script>\n"
        "    <!-- SEO-SCHEMA:END -->"
    )
    text = re.sub(
        r"\s*<!-- SEO-SCHEMA:BEGIN -->.*?<!-- SEO-SCHEMA:END -->",
        f"\n{schema_block}",
        text,
        count=1,
        flags=re.DOTALL,
    ) if "<!-- SEO-SCHEMA:BEGIN -->" in text else re.sub(
        r"\s*<script\s+type=\"application/ld\+json\">\s*\{\s*\"@context\".*?</script>",
        f"\n{schema_block}",
        text,
        count=1,
        flags=re.DOTALL,
    )
    if "<!-- SEO-SCHEMA:BEGIN -->" not in text:
        text = text.replace("</head>", f"{schema_block}\n</head>", 1)

    href_map = {
        "home": "/",
        "shop": "/shop/",
        "about": "/about.html",
        "socials": "/about.html#social-media",
        "reptilog": "https://reptilog.app/",
        "care": "/care-guides/",
        "faq": "/shipping.html",
    }
    for page, href in href_map.items():
        text = re.sub(
            rf'<a\s+href="#"([^>]*\bdata-page="{re.escape(page)}"[^>]*)>',
            f'<a href="{href}"\\1>',
            text,
        )

    text = text.replace(
        "<h1>Red Rocks Exotic Reptiles</h1>",
        "<h1>Red Rocks Exotic Reptiles — Colorado Reptile Store</h1>",
        1,
    )
    text = text.replace(
        "How to Purchase: We currently do not have a store portal. All sales are handled via PayPal Goods & Services and Venmo Business.",
        "How to Purchase: Add shippable products to the secure online cart and complete payment through Stripe. Live animals and local-pickup items may require direct confirmation before purchase.",
    )
    text = text.replace(
        "<li>PayPal Goods &amp; Services</li>\n                    <li>Venmo Business</li>\n                    <li>MorphMarket</li>",
        "<li>Secure online checkout through Stripe</li>\n                    <li>Major cards and supported digital wallets</li>\n                    <li>MorphMarket for eligible live-animal listings</li>",
    )

    noscript = (
        "    <!-- SEO-NOSCRIPT:BEGIN -->\n"
        "    <noscript><div class=\"section\"><h2>Browse Red Rocks Exotic Reptiles</h2>"
        "<p>This site works best with JavaScript, but all current products and business information remain available on our crawlable pages.</p>"
        "<p><a href=\"/shop/\">Online reptile store</a> · <a href=\"/care-guides/\">Reptile care guides</a> · "
        "<a href=\"/contact.html\">Contact and local pickup</a></p></div></noscript>\n"
        "    <!-- SEO-NOSCRIPT:END -->"
    )
    if "<!-- SEO-NOSCRIPT:BEGIN -->" not in text:
        text = text.replace("<body>", f"<body>\n{noscript}", 1)

    if text != original:
        INDEX_PATH.write_text(text, encoding="utf-8")
        print("Updated index.html SEO metadata and crawlable navigation")


def patch_storefront_assets() -> None:
    js = STOREFRONT_JS_PATH.read_text(encoding="utf-8")
    original_js = js
    helper = """
    function productDetailUrl(product) {
        const slug = String(product?.slug || `item-${product?.item_id || 'product'}`);
        return `/products/${encodeURIComponent(slug)}.html`;
    }

    function syncProductDetailLink(card, product) {
        if (!card || !product) return;
        const title = card.querySelector('.product-info h3, h3');
        if (!title) return;
        let link = title.querySelector('a.storefront-product-link');
        if (!link) {
            link = document.createElement('a');
            link.className = 'storefront-product-link';
            link.textContent = title.textContent.trim();
            title.replaceChildren(link);
        }
        link.href = productDetailUrl(product);
        link.setAttribute('aria-label', `View details for ${product.public_name}`);
    }
"""
    if "function productDetailUrl(product)" not in js:
        match = re.search(r'(?m)^\s*function productPrice\(product\) \{', js)
        if not match:
            raise RuntimeError("Could not locate productPrice in shop/storefront.js")
        js = js[:match.start()] + helper + "\n" + js[match.start():]
    js = re.sub(
        r'(function markCardAvailability\(card, product = null\) \{\n)(\s*)(const info = card\.querySelector\(\'.product-info\'\) \|\| card;)',
        r'\1\2if (product) syncProductDetailLink(card, product);\n\2\3',
        js,
        count=1,
    )
    if js != original_js:
        STOREFRONT_JS_PATH.write_text(js, encoding="utf-8")
        print("Added crawlable product links to the interactive storefront")

    css = STOREFRONT_CSS_PATH.read_text(encoding="utf-8")
    if "/* SEO product detail links */" not in css:
        css += """

/* SEO product detail links */
.storefront-product-link {
    color: inherit;
    text-decoration: none;
}
.storefront-product-link:hover,
.storefront-product-link:focus-visible {
    color: var(--accent, #9e1403);
    text-decoration: underline;
    text-underline-offset: 3px;
}
"""
        STOREFRONT_CSS_PATH.write_text(css, encoding="utf-8")


def page_head(title: str, description: str, canonical: str, *, image: str = DEFAULT_IMAGE, page_type: str = "website", keywords: str = "") -> str:
    keyword_meta = f'  <meta name="keywords" content="{escape(keywords)}">\n' if keywords else ""
    return f"""  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description)}">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
{keyword_meta}  <link rel="canonical" href="{escape(canonical)}">
  <meta property="og:type" content="{escape(page_type)}">
  <meta property="og:site_name" content="{BUSINESS_NAME}">
  <meta property="og:title" content="{escape(title)}">
  <meta property="og:description" content="{escape(description)}">
  <meta property="og:url" content="{escape(canonical)}">
  <meta property="og:image" content="{escape(image)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape(title)}">
  <meta name="twitter:description" content="{escape(description)}">
  <meta name="twitter:image" content="{escape(image)}">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png">
  <link rel="stylesheet" href="/shop/seo.css">"""


def site_header() -> str:
    return """<header class="site-header">
  <a class="brand" href="/"><img src="/images/Logo.svg" alt=""><span><strong>Red Rocks</strong> Exotic Reptiles</span></a>
  <nav aria-label="Primary navigation">
    <a href="/shop/">Shop</a>
    <a href="/shop/reptiles.html">Reptiles</a>
    <a href="/shop/reptile-supplies.html">Supplies</a>
    <a href="/care-guides/">Care Guides</a>
    <a href="/contact.html">Contact</a>
  </nav>
</header>"""


def site_footer() -> str:
    return f"""<footer class="site-footer">
  <div><strong>{BUSINESS_NAME}</strong><br>Colorado reptile store, breeder, and husbandry supplier.</div>
  <div><a href="tel:9704001278">{BUSINESS_PHONE_DISPLAY}</a><br><a href="mailto:{BUSINESS_EMAIL}">{BUSINESS_EMAIL}</a></div>
  <div><a href="/shipping.html">Shipping & local pickup</a><br><a href="/policies/privacy-policy.html">Privacy</a> · <a href="/policies/terms-of-service.html">Terms</a></div>
</footer>"""


def breadcrumb_schema(items: list[tuple[str, str]]) -> dict[str, Any]:
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": index, "name": name, "item": url}
            for index, (name, url) in enumerate(items, start=1)
        ],
    }


def breadcrumb_html(items: list[tuple[str, str]]) -> str:
    links = []
    for index, (name, url) in enumerate(items):
        if index == len(items) - 1:
            links.append(f"<span aria-current=\"page\">{escape(name)}</span>")
        else:
            links.append(f"<a href=\"{escape(url)}\">{escape(name)}</a>")
    return '<nav class="breadcrumbs" aria-label="Breadcrumb">' + " <span aria-hidden=\"true\">/</span> ".join(links) + "</nav>"


def product_card(product: dict[str, Any]) -> str:
    name = compact_text(product.get("public_name"), "Website product")
    image = absolute_url(compact_text(product.get("image_url")))
    price = compact_text(product.get("display_price_text"), "Contact for pricing")
    stock = "In stock" if product.get("in_stock") else "Out of stock"
    url = product_url(product)
    pickup = '<span class="pill">Local pickup only</span>' if product.get("local_pickup_only") else ""
    return f"""<article class="product-card">
  <a class="product-image" href="{escape(url)}"><img src="{escape(image)}" alt="{escape(name)}" loading="lazy" decoding="async"></a>
  <div class="product-copy">
    <p class="eyebrow">{escape(CATEGORY_LABELS.get(compact_text(product.get('store_category')), 'Reptile shop'))}</p>
    <h2><a href="{escape(url)}">{escape(name)}</a></h2>
    <p>{escape(product_description(product))}</p>
    <div class="product-meta"><strong>{escape(price)}</strong><span class="stock {'available' if product.get('in_stock') else ''}">{stock}</span>{pickup}</div>
  </div>
</article>"""


def product_schema(product: dict[str, Any]) -> dict[str, Any]:
    name = compact_text(product.get("public_name"), "Website product")
    images = product.get("image_urls") if isinstance(product.get("image_urls"), list) else []
    images = [absolute_url(compact_text(value)) for value in images if compact_text(value)]
    if not images:
        images = [absolute_url(compact_text(product.get("image_url")))]
    data: dict[str, Any] = {
        "@type": "Product",
        "@id": f"{product_url(product)}#product",
        "name": name,
        "description": product_description(product),
        "image": images,
        "sku": str(product.get("item_id", "")),
        "category": CATEGORY_LABELS.get(compact_text(product.get("store_category")), "Reptile shop product"),
        "brand": {"@type": "Brand", "name": BUSINESS_NAME},
        "url": product_url(product),
    }
    try:
        price = float(product.get("price") or 0)
    except (TypeError, ValueError):
        price = 0
    if price > 0:
        offer: dict[str, Any] = {
            "@type": "Offer",
            "url": product_url(product),
            "priceCurrency": "USD",
            "price": f"{price:.2f}",
            "availability": availability_schema(product),
            "itemCondition": "https://schema.org/NewCondition",
            "seller": {"@id": f"{BASE_URL}/#business"},
        }
        if product.get("local_pickup_only"):
            offer["availableDeliveryMethod"] = "https://purl.org/goodrelations/v1#DeliveryModePickUp"
            offer["areaServed"] = {"@type": "State", "name": "Colorado"}
        data["offers"] = offer
    return data


def write_product_pages(products: list[dict[str, Any]]) -> list[str]:
    PRODUCTS_DIR.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []
    active_files: set[str] = set()
    for product in products:
        slug = compact_text(product.get("slug"), f"item-{product.get('item_id', 'product')}")
        filename = f"{slug}.html"
        active_files.add(filename)
        name = compact_text(product.get("public_name"), "Website product")
        description = product_description(product)
        canonical = product_url(product)
        image = absolute_url(compact_text(product.get("image_url")))
        group_slug = product_group(product)
        group = CATEGORY_GROUPS[group_slug]
        price = compact_text(product.get("display_price_text"), "Contact for pricing")
        stock = "In stock" if product.get("in_stock") else "Out of stock"
        images = product.get("image_urls") if isinstance(product.get("image_urls"), list) else []
        gallery = [absolute_url(compact_text(value)) for value in images if compact_text(value)] or [image]
        gallery_html = "".join(
            f'<img src="{escape(url)}" alt="{escape(name)} product photo {index}" loading="lazy" decoding="async">'
            for index, url in enumerate(gallery, start=1)
        )
        if product.get("local_pickup_only"):
            fulfillment = "<p class=\"notice\"><strong>Colorado local pickup only.</strong> Contact us to confirm quantity and arrange pickup.</p>"
        elif product.get("purchase_mode") == "inquiry":
            fulfillment = "<p class=\"notice\"><strong>Contact to order.</strong> Availability and fulfillment will be confirmed before payment.</p>"
        else:
            fulfillment = "<p class=\"notice\"><strong>Online checkout available.</strong> Shipping and applicable tax are calculated during secure Stripe checkout.</p>"
        action = (
            f'<a class="button" href="/?product={quote(slug)}#shop">Shop this product</a>'
            if product.get("purchase_mode") == "checkout" and product.get("in_stock")
            else f'<a class="button" href="mailto:{BUSINESS_EMAIL}?subject={quote("Inquiry about " + name)}">Ask about availability</a>'
        )
        breadcrumbs = [
            ("Home", f"{BASE_URL}/"),
            ("Shop", f"{BASE_URL}/shop/"),
            (group["short"], f"{BASE_URL}/shop/{group_slug}.html"),
            (name, canonical),
        ]
        graph = {
            "@context": "https://schema.org",
            "@graph": [product_schema(product), breadcrumb_schema(breadcrumbs), business_schema()],
        }
        body = f"""<!DOCTYPE html>
<html lang="en-US">
<head>
{page_head(f"{name} | {BUSINESS_NAME}", description, canonical, image=image, page_type="product", keywords=f"{name}, reptile store Colorado, {group['keywords']}")}
  <script type="application/ld+json">{json_script(graph)}</script>
</head>
<body>
{GENERATED_COMMENT}
{site_header()}
<main class="page-shell">
  {breadcrumb_html(breadcrumbs)}
  <article class="product-detail">
    <div class="product-gallery">{gallery_html}</div>
    <div class="product-detail-copy">
      <p class="eyebrow">{escape(group['short'])}</p>
      <h1>{escape(name)}</h1>
      <p class="lead">{escape(description)}</p>
      <div class="price-line"><strong>{escape(price)}</strong><span class="stock {'available' if product.get('in_stock') else ''}">{stock}</span></div>
      {fulfillment}
      {action}
      <dl class="details-list">
        <div><dt>Seller</dt><dd>{BUSINESS_NAME}</dd></div>
        <div><dt>Location</dt><dd>Colorado, United States</dd></div>
        <div><dt>Product ID</dt><dd>{escape(product.get('item_id'))}</dd></div>
      </dl>
    </div>
  </article>
  <section class="content-panel">
    <h2>Ordering from a Colorado reptile store</h2>
    <p>Red Rocks Exotic Reptiles offers secure online checkout for eligible products, nationwide shipping for shippable goods, and local pickup by arrangement in Colorado. Live-animal availability and weather-safe shipping are always confirmed before fulfillment.</p>
    <p><a href="/shipping.html">Read shipping and local-pickup information</a> or <a href="/contact.html">contact Red Rocks Exotic Reptiles</a>.</p>
  </section>
</main>
{site_footer()}
</body>
</html>
"""
        (PRODUCTS_DIR / filename).write_text(body, encoding="utf-8")
        generated.append(canonical)

    for existing in PRODUCTS_DIR.glob("*.html"):
        if existing.name not in active_files and GENERATED_COMMENT in existing.read_text(encoding="utf-8", errors="ignore"):
            existing.unlink()
    return generated


def write_category_pages(products: list[dict[str, Any]]) -> list[str]:
    SHOP_DIR.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []
    by_group: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for product in products:
        by_group[product_group(product)].append(product)
    for group_products in by_group.values():
        group_products.sort(key=lambda row: (not bool(row.get("in_stock")), int(row.get("display_order") or 9999), compact_text(row.get("public_name")).lower()))

    category_links = "".join(
        f'<a class="category-card" href="/shop/{slug}.html"><h2>{escape(config["short"])}</h2><p>{escape(config["description"])}</p></a>'
        for slug, config in CATEGORY_GROUPS.items()
    )
    all_cards = "".join(product_card(product) for product in products)
    shop_url = f"{BASE_URL}/shop/"
    shop_items = [
        {"@type": "ListItem", "position": index, "url": product_url(product), "name": compact_text(product.get("public_name"))}
        for index, product in enumerate(products, start=1)
    ]
    shop_graph = {
        "@context": "https://schema.org",
        "@graph": [
            business_schema(),
            {"@type": "CollectionPage", "@id": f"{shop_url}#page", "url": shop_url, "name": "Colorado Reptile Store", "description": "Current reptiles, feeders, supplies, plants, and entomology products from Red Rocks Exotic Reptiles."},
            {"@type": "ItemList", "itemListElement": shop_items},
            breadcrumb_schema([("Home", f"{BASE_URL}/"), ("Shop", shop_url)]),
        ],
    }
    shop_html = f"""<!DOCTYPE html>
<html lang="en-US">
<head>
{page_head("Colorado Reptile Store | Shop Red Rocks Exotic Reptiles", "Browse current reptiles, feeder insects, reptile supplies, aquatic plants, and custom enclosure accessories from Red Rocks Exotic Reptiles in Colorado.", shop_url, keywords="reptile store Colorado, reptiles for sale, reptile supplies, feeder insects")}
  <script type="application/ld+json">{json_script(shop_graph)}</script>
</head>
<body>
{GENERATED_COMMENT}
{site_header()}
<main class="page-shell">
  {breadcrumb_html([("Home", f"{BASE_URL}/"), ("Shop", shop_url)])}
  <section class="page-hero">
    <p class="eyebrow">Colorado reptile store</p>
    <h1>Shop Red Rocks Exotic Reptiles</h1>
    <p class="lead">Browse live inventory from our Colorado reptile business, including captive-bred reptiles, feeder insects, husbandry supplies, aquatic plants, and custom enclosure products.</p>
  </section>
  <section class="category-grid" aria-label="Shop categories">{category_links}</section>
  <section class="section-heading"><h2>Current inventory</h2><p>Availability and prices are generated from the same store inventory used by the interactive storefront.</p></section>
  <div class="product-list">{all_cards or '<p>No products are currently published. Please check back soon.</p>'}</div>
</main>
{site_footer()}
</body>
</html>
"""
    (SHOP_DIR / "index.html").write_text(shop_html, encoding="utf-8")
    generated.append(shop_url)

    for slug, config in CATEGORY_GROUPS.items():
        group_products = by_group.get(slug, [])
        canonical = f"{BASE_URL}/shop/{slug}.html"
        breadcrumbs = [("Home", f"{BASE_URL}/"), ("Shop", shop_url), (config["short"], canonical)]
        item_list = [
            {"@type": "ListItem", "position": index, "url": product_url(product), "name": compact_text(product.get("public_name"))}
            for index, product in enumerate(group_products, start=1)
        ]
        graph = {
            "@context": "https://schema.org",
            "@graph": [
                business_schema(),
                {"@type": "CollectionPage", "@id": f"{canonical}#page", "url": canonical, "name": config["title"], "description": config["description"]},
                {"@type": "ItemList", "itemListElement": item_list},
                breadcrumb_schema(breadcrumbs),
            ],
        }
        cards = "".join(product_card(product) for product in group_products)
        page = f"""<!DOCTYPE html>
<html lang="en-US">
<head>
{page_head(f"{config['title']} | {BUSINESS_NAME}", config['description'], canonical, keywords=config['keywords'])}
  <script type="application/ld+json">{json_script(graph)}</script>
</head>
<body>
{GENERATED_COMMENT}
{site_header()}
<main class="page-shell">
  {breadcrumb_html(breadcrumbs)}
  <section class="page-hero">
    <p class="eyebrow">Red Rocks Exotic Reptiles</p>
    <h1>{escape(config['title'])}</h1>
    <p class="lead">{escape(config['description'])}</p>
  </section>
  <div class="product-list">{cards or '<section class="content-panel"><h2>Check back soon</h2><p>No products in this category are currently published. Contact us for upcoming availability.</p></section>'}</div>
</main>
{site_footer()}
</body>
</html>
"""
        (SHOP_DIR / f"{slug}.html").write_text(page, encoding="utf-8")
        generated.append(canonical)
    return generated


def extract_tag(text: str, tag: str, class_name: str | None = None) -> str:
    class_part = rf'[^>]*class="[^"]*\b{re.escape(class_name)}\b[^"]*"[^>]*' if class_name else "[^>]*"
    match = re.search(rf"<{tag}{class_part}>(.*?)</{tag}>", text, flags=re.IGNORECASE | re.DOTALL)
    return compact_text(re.sub(r"<[^>]+>", " ", html.unescape(match.group(1)))) if match else ""


def patch_care_guides() -> list[str]:
    CARE_DIR.mkdir(parents=True, exist_ok=True)
    guide_rows: list[dict[str, str]] = []
    for path in sorted(CARE_DIR.glob("*.html")):
        if path.name == "index.html":
            continue
        text = path.read_text(encoding="utf-8")
        original = text
        title = extract_tag(text, "h1") or path.stem.replace("-", " ").title()
        scientific_name = extract_tag(text, "p", "sciname")
        description_match = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', text, flags=re.IGNORECASE)
        description = compact_text(description_match.group(1) if description_match else "", f"Practical {title.lower()} husbandry and care guide from {BUSINESS_NAME}.")
        canonical = f"{BASE_URL}/care-guides/{path.name}"
        page_title = f"{title} | Breeder-Backed Reptile Care Guide"
        text = re.sub(r"<title>.*?</title>", f"<title>{escape(page_title)}</title>", text, count=1, flags=re.DOTALL)
        head_additions = f"""
  <!-- SEO-GUIDE:BEGIN -->
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="{BUSINESS_NAME}">
  <meta property="og:title" content="{escape(page_title)}">
  <meta property="og:description" content="{escape(description)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{DEFAULT_IMAGE}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape(page_title)}">
  <meta name="twitter:description" content="{escape(description)}">
  <meta name="twitter:image" content="{DEFAULT_IMAGE}">
  <script type="application/ld+json">{json_script({
      '@context': 'https://schema.org',
      '@graph': [
          {
              '@type': 'Article',
              '@id': f'{canonical}#article',
              'headline': title,
              'description': description,
              'url': canonical,
              'mainEntityOfPage': canonical,
              'author': {'@id': f'{BASE_URL}/#business'},
              'publisher': {'@id': f'{BASE_URL}/#business'},
              'about': scientific_name or title,
              'inLanguage': 'en-US',
              'image': DEFAULT_IMAGE,
          },
          breadcrumb_schema([('Home', f'{BASE_URL}/'), ('Care Guides', f'{BASE_URL}/care-guides/'), (title, canonical)]),
          business_schema(),
      ],
  })}</script>
  <!-- SEO-GUIDE:END -->"""
        text = re.sub(r"\s*<!-- SEO-GUIDE:BEGIN -->.*?<!-- SEO-GUIDE:END -->", head_additions, text, count=1, flags=re.DOTALL)
        if "<!-- SEO-GUIDE:BEGIN -->" not in text:
            text = text.replace("</head>", f"{head_additions}\n</head>", 1)
        text = text.replace('href="../index.html#care"', 'href="/care-guides/"')
        if text != original:
            path.write_text(text, encoding="utf-8")
        guide_rows.append({"title": title, "scientific": scientific_name, "description": description, "url": canonical, "filename": path.name})

    guide_cards = "".join(
        f'<article class="guide-card"><p class="eyebrow">{escape(row["scientific"] or "Reptile care")}</p><h2><a href="/{escape("care-guides/" + row["filename"])}">{escape(row["title"])}</a></h2><p>{escape(row["description"])}</p><a class="text-link" href="/{escape("care-guides/" + row["filename"])}">Read care guide →</a></article>'
        for row in guide_rows
    )
    canonical = f"{BASE_URL}/care-guides/"
    graph = {
        "@context": "https://schema.org",
        "@graph": [
            business_schema(),
            {"@type": "CollectionPage", "url": canonical, "name": "Reptile Care Guides", "description": "Breeder-backed reptile husbandry guides from Red Rocks Exotic Reptiles."},
            {"@type": "ItemList", "itemListElement": [{"@type": "ListItem", "position": index, "url": row["url"], "name": row["title"]} for index, row in enumerate(guide_rows, start=1)]},
            breadcrumb_schema([("Home", f"{BASE_URL}/"), ("Care Guides", canonical)]),
        ],
    }
    index_html = f"""<!DOCTYPE html>
<html lang="en-US">
<head>
{page_head("Reptile Care Guides | Red Rocks Exotic Reptiles", "Browse breeder-backed reptile care guides covering enclosure setup, temperature, humidity, diet, behavior, and health monitoring.", canonical, keywords="reptile care guides, gecko care guide, skink care guide, snake care guide")}
  <script type="application/ld+json">{json_script(graph)}</script>
</head>
<body>
{GENERATED_COMMENT}
{site_header()}
<main class="page-shell">
  {breadcrumb_html([("Home", f"{BASE_URL}/"), ("Care Guides", canonical)])}
  <section class="page-hero"><p class="eyebrow">Education from experienced keepers</p><h1>Reptile Care Guides</h1><p class="lead">Practical reptile husbandry references covering enclosure setup, temperature, humidity, diet, handling, and health monitoring.</p></section>
  <div class="guide-grid">{guide_cards}</div>
</main>
{site_footer()}
</body>
</html>
"""
    (CARE_DIR / "index.html").write_text(index_html, encoding="utf-8")
    return [canonical, *[row["url"] for row in guide_rows]]


def write_business_pages() -> list[str]:
    pages: list[tuple[str, str, str]] = []
    about_url = f"{BASE_URL}/about.html"
    about_graph = {"@context": "https://schema.org", "@graph": [business_schema(), {"@type": "AboutPage", "url": about_url, "name": f"About {BUSINESS_NAME}", "about": {"@id": f"{BASE_URL}/#business"}}, breadcrumb_schema([("Home", f"{BASE_URL}/"), ("About", about_url)])]}
    about = f"""<!DOCTYPE html><html lang="en-US"><head>
{page_head(f"About Our Colorado Reptile Store | {BUSINESS_NAME}", "Learn about Red Rocks Exotic Reptiles, a veteran-owned Colorado reptile breeder and store focused on ethical husbandry, education, and responsible reptile keeping.", about_url, keywords="Colorado reptile breeder, veteran owned reptile store, ethical reptile breeder")}
<script type="application/ld+json">{json_script(about_graph)}</script></head><body>{GENERATED_COMMENT}{site_header()}<main class="page-shell">{breadcrumb_html([("Home", f"{BASE_URL}/"), ("About", about_url)])}<section class="page-hero"><p class="eyebrow">Colorado-based · Veteran owned</p><h1>About Red Rocks Exotic Reptiles</h1><p class="lead">We are a Colorado reptile business built by keepers who prioritize clean husbandry, responsible breeding, honest education, and long-term support.</p></section><section class="content-panel"><h2>Our reptile business</h2><p>Red Rocks Exotic Reptiles began as a reptile-keeping hobby and grew into a business in 2023. We work with geckos, skinks, arboreal lizards, snakes, feeder insects, aquatic plants, and custom husbandry products.</p><p>We are proud to be a woman-, veteran-, Hispanic-, and Native American-owned company. Our goal is to help customers choose appropriate animals and supplies while promoting responsible care.</p><h2>What customers can expect</h2><ul><li>Ethically bred and responsibly sourced animals</li><li>Transparent information about availability and care requirements</li><li>Practical husbandry support before and after a purchase</li><li>Secure online checkout for eligible products</li><li>Weather-conscious live-animal shipping and Colorado pickup options</li></ul></section><section class="content-panel" id="social-media"><h2>Follow our reptiles and current inventory</h2><p><a href="{SOCIAL_URLS[0]}" rel="me">Instagram</a> · <a href="{SOCIAL_URLS[1]}" rel="me">Facebook</a> · <a href="{SOCIAL_URLS[2]}" rel="me">TikTok</a> · <a href="{SOCIAL_URLS[4]}" rel="me">MorphMarket</a></p></section></main>{site_footer()}</body></html>"""
    pages.append(("about.html", about, about_url))

    contact_url = f"{BASE_URL}/contact.html"
    contact_graph = {"@context": "https://schema.org", "@graph": [business_schema(), {"@type": "ContactPage", "url": contact_url, "name": f"Contact {BUSINESS_NAME}", "mainEntity": {"@id": f"{BASE_URL}/#business"}}, breadcrumb_schema([("Home", f"{BASE_URL}/"), ("Contact", contact_url)])]}
    contact = f"""<!DOCTYPE html><html lang="en-US"><head>
{page_head(f"Contact a Colorado Reptile Store | {BUSINESS_NAME}", "Contact Red Rocks Exotic Reptiles for current reptile availability, online orders, feeder pickup, shipping questions, and Colorado reptile-show pickup.", contact_url, keywords="reptile store near me Colorado, contact reptile breeder, reptile pickup Colorado")}
<script type="application/ld+json">{json_script(contact_graph)}</script></head><body>{GENERATED_COMMENT}{site_header()}<main class="page-shell">{breadcrumb_html([("Home", f"{BASE_URL}/"), ("Contact", contact_url)])}<section class="page-hero"><p class="eyebrow">Questions, availability, and pickup</p><h1>Contact Red Rocks Exotic Reptiles</h1><p class="lead">Reach our Colorado reptile business for live-animal availability, feeder quantities, product questions, shipping, or pickup arrangements.</p></section><section class="contact-grid"><article class="content-panel"><h2>Call or text</h2><p><a class="contact-link" href="tel:9704001278">{BUSINESS_PHONE_DISPLAY}</a></p><p>For urgent questions about an active order, include your order number.</p></article><article class="content-panel"><h2>Email</h2><p><a class="contact-link" href="mailto:{BUSINESS_EMAIL}">{BUSINESS_EMAIL}</a></p><p>Include the product or animal name and your ZIP code when asking about shipping.</p></article><article class="content-panel"><h2>Colorado local pickup</h2><p>Local pickup is available by prior arrangement. Red Rocks Exotic Reptiles does not operate a public walk-in retail storefront, so please confirm a pickup time and location before traveling.</p></article><article class="content-panel"><h2>Reptile shows</h2><p>We vend at Colorado reptile and exotic-animal events. Contact us before a show to reserve eligible products for show pickup.</p></article></section></main>{site_footer()}</body></html>"""
    pages.append(("contact.html", contact, contact_url))

    shipping_url = f"{BASE_URL}/shipping.html"
    shipping_graph = {"@context": "https://schema.org", "@graph": [business_schema(), {"@type": "WebPage", "url": shipping_url, "name": "Reptile Shipping, Local Pickup & Ordering", "about": {"@id": f"{BASE_URL}/#business"}}, breadcrumb_schema([("Home", f"{BASE_URL}/"), ("Shipping & Pickup", shipping_url)])]}
    shipping = f"""<!DOCTYPE html><html lang="en-US"><head>
{page_head(f"Reptile Shipping & Local Pickup | {BUSINESS_NAME}", "Review secure checkout, reptile and product shipping, weather holds, live-arrival expectations, feeder pickup, and Colorado show-pickup information.", shipping_url, keywords="reptile shipping Colorado, live reptile shipping, feeder insect pickup Colorado")}
<script type="application/ld+json">{json_script(shipping_graph)}</script></head><body>{GENERATED_COMMENT}{site_header()}<main class="page-shell">{breadcrumb_html([("Home", f"{BASE_URL}/"), ("Shipping & Pickup", shipping_url)])}<section class="page-hero"><p class="eyebrow">Safe fulfillment</p><h1>Shipping, Checkout & Colorado Pickup</h1><p class="lead">How Red Rocks Exotic Reptiles handles secure checkout, shippable products, live animals, feeder insects, and local pickup.</p></section><div class="guide-grid"><article class="content-panel"><h2>Secure checkout</h2><p>Eligible products use Stripe for secure card and supported wallet payments. Shipping and applicable sales tax are calculated from the delivery address during checkout.</p></article><article class="content-panel"><h2>Live-animal shipping</h2><p>Eligible live animals are shipped using appropriate insulated packaging and temperature controls. Weather, carrier service, and safe receiving conditions may require a shipping hold or coordinated delivery date.</p></article><article class="content-panel"><h2>Live-arrival concerns</h2><p>Inspect live shipments promptly. Contact us immediately with clear photos and order details if there is a concern on arrival so the situation can be documented and reviewed.</p></article><article class="content-panel"><h2>Feeder insects</h2><p>Live feeder insects and cultures are Colorado local-pickup items. They are not offered through standard parcel shipping.</p></article><article class="content-panel"><h2>Local and show pickup</h2><p>Pickup is available only by prior arrangement. We also offer reserved pickup at eligible Colorado reptile shows where we are vending.</p></article><article class="content-panel"><h2>Questions before ordering</h2><p>Contact us with the item name and destination ZIP code for shipping or availability questions.</p><p><a href="/contact.html">Contact Red Rocks Exotic Reptiles</a></p></article></div></main>{site_footer()}</body></html>"""
    pages.append(("shipping.html", shipping, shipping_url))

    for filename, content, url in pages:
        (ROOT / filename).write_text(content, encoding="utf-8")
    return [url for _, _, url in pages]


def write_robots() -> None:
    (ROOT / "robots.txt").write_text(
        "User-agent: *\nAllow: /\n\nSitemap: https://rrereptiles.com/sitemap.xml\n",
        encoding="utf-8",
    )


def write_llms(products: list[dict[str, Any]]) -> None:
    category_lines = "\n".join(f"- [{config['short']}]({BASE_URL}/shop/{slug}.html): {config['description']}" for slug, config in CATEGORY_GROUPS.items())
    featured = "\n".join(
        f"- [{compact_text(product.get('public_name'))}]({product_url(product)}): {product_description(product)}"
        for product in products[:25]
    )
    content = f"""# {BUSINESS_NAME}

> Colorado reptile store and ethical breeder offering captive-bred reptiles, feeder insects, reptile supplies, aquatic plants, entomology art, and breeder-backed care information.

## Official information

- Website: {BASE_URL}/
- Shop: {BASE_URL}/shop/
- Care guides: {BASE_URL}/care-guides/
- Contact: {BASE_URL}/contact.html
- Shipping and local pickup: {BASE_URL}/shipping.html
- Email: {BUSINESS_EMAIL}
- Phone: {BUSINESS_PHONE_DISPLAY}
- Service area: Colorado and the United States for eligible shippable products
- Local pickup: By prior arrangement; no public walk-in storefront

## Shop categories

{category_lines}

## Current product pages

{featured}

## Content use notes

Product availability and prices can change. Use each product page and the secure storefront as the current source. Care guides are general educational references and are not veterinary diagnosis.
"""
    (ROOT / "llms.txt").write_text(content, encoding="utf-8")


def write_sitemap(urls: Iterable[tuple[str, str | None]]) -> None:
    unique: dict[str, str | None] = {}
    for url, lastmod in urls:
        unique[url] = lastmod
    entries = []
    for url in sorted(unique, key=lambda value: (value != f"{BASE_URL}/", value)):
        lastmod = unique[url]
        lastmod_xml = f"\n    <lastmod>{escape(lastmod)}</lastmod>" if lastmod else ""
        entries.append(f"  <url>\n    <loc>{escape(url)}</loc>{lastmod_xml}\n  </url>")
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "\n".join(entries) + "\n</urlset>\n"
    (ROOT / "sitemap.xml").write_text(xml, encoding="utf-8")


def validate_output(products: list[dict[str, Any]]) -> None:
    checks = [
        INDEX_PATH,
        ROOT / "robots.txt",
        ROOT / "sitemap.xml",
        ROOT / "llms.txt",
        SHOP_DIR / "index.html",
        CARE_DIR / "index.html",
        ROOT / "about.html",
        ROOT / "contact.html",
        ROOT / "shipping.html",
    ]
    missing = [str(path.relative_to(ROOT)) for path in checks if not path.exists()]
    if missing:
        raise RuntimeError(f"Missing generated SEO files: {', '.join(missing)}")
    index = INDEX_PATH.read_text(encoding="utf-8")
    if "SEO-SCHEMA:BEGIN" not in index or "Colorado Reptile Store" not in index:
        raise RuntimeError("index.html does not contain the generated SEO metadata.")
    sitemap = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
    if f"{BASE_URL}/shop/" not in sitemap or f"{BASE_URL}/care-guides/" not in sitemap:
        raise RuntimeError("sitemap.xml is missing key landing pages.")
    if products and not any(PRODUCTS_DIR.glob("*.html")):
        raise RuntimeError("No product pages were generated from a non-empty catalog.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-fixture", type=Path, help="Use a local JSON catalog fixture instead of Supabase.")
    parser.add_argument("--allow-catalog-failure", action="store_true", help="Keep existing product pages if the catalog is temporarily unavailable.")
    args = parser.parse_args()

    patch_index()
    patch_storefront_assets()
    business_urls = write_business_pages()
    care_urls = patch_care_guides()
    write_robots()

    products: list[dict[str, Any]] = []
    product_urls: list[str] = []
    shop_urls: list[str] = []
    try:
        products = fetch_catalog(args.catalog_fixture)
        products.sort(key=lambda row: (not bool(row.get("in_stock")), int(row.get("display_order") or 9999), compact_text(row.get("public_name")).lower()))
        product_urls = write_product_pages(products)
        shop_urls = write_category_pages(products)
        write_llms(products)
    except RuntimeError as error:
        if not args.allow_catalog_failure:
            raise
        print(f"Warning: {error}", file=sys.stderr)
        if not (SHOP_DIR / "index.html").exists():
            raise
        write_llms([])
        product_urls = [f"{BASE_URL}/products/{path.name}" for path in PRODUCTS_DIR.glob("*.html")]
        shop_urls = [f"{BASE_URL}/shop/", *[f"{BASE_URL}/shop/{slug}.html" for slug in CATEGORY_GROUPS]]

    urls: list[tuple[str, str | None]] = [(f"{BASE_URL}/", TODAY)]
    urls.extend((url, TODAY) for url in business_urls + care_urls + shop_urls)
    product_by_url = {product_url(product): compact_text(product.get("updated_at"))[:10] or TODAY for product in products}
    urls.extend((url, product_by_url.get(url, TODAY)) for url in product_urls)
    urls.extend([
        (f"{BASE_URL}/policies/privacy-policy.html", None),
        (f"{BASE_URL}/policies/terms-of-service.html", None),
    ])
    write_sitemap(urls)
    validate_output(products)
    print(f"Generated SEO output for {len(products)} storefront products and {len(care_urls) - 1} care guides.")


if __name__ == "__main__":
    main()
